export const languageOptions = [
  { key: "af", name: "Afrikaans" },
  { key: "sq", name: "Albanian" },
  { key: "am", name: "Amharic" },
  { key: "ar", name: "Arabic" },
  { key: "hy", name: "Armenian" },
  { key: "az", name: "Azerbaijani" },
  { key: "eu", name: "Basque" },
  { key: "be", name: "Belarusian" },
  { key: "bn", name: "Bengali" },
  { key: "bs", name: "Bosnian" },
  { key: "bg", name: "Bulgarian" },
  { key: "ca", name: "Catalan" },
  { key: "ceb", name: "Cebuano" },
  { key: "zh-CN", name: "Chinese (Simplified)" },
  { key: "zh-TW", name: "Chinese (Traditional)" },
  { key: "co", name: "Corsican" },
  { key: "hr", name: "Croatian" },
  { key: "cs", name: "Czech" },
  { key: "da", name: "Danish" },
  { key: "nl", name: "Dutch" },
  { key: "en", name: "English" },
  { key: "eo", name: "Esperanto" },
  { key: "et", name: "Estonian" },
  { key: "fi", name: "Finnish" },
  { key: "fr", name: "French" },
  { key: "fy", name: "Frisian" },
  { key: "gl", name: "Galician" },
  { key: "ka", name: "Georgian" },
  { key: "de", name: "German" },
  { key: "el", name: "Greek" },
  { key: "gu", name: "Gujarati" },
  { key: "ht", name: "Haitian Creole" },
  { key: "ha", name: "Hausa" },
  { key: "haw", name: "Hawaiian" },
  { key: "he", name: "Hebrew" },
  { key: "hi", name: "Hindi" },
  { key: "hmn", name: "Hmong" },
  { key: "hu", name: "Hungarian" },
  { key: "is", name: "Icelandic" },
  { key: "ig", name: "Igbo" },
  { key: "id", name: "Indonesian" },
  { key: "ga", name: "Irish" },
  { key: "it", name: "Italian" },
  { key: "ja", name: "Japanese" },
  { key: "jw", name: "Javanese" },
  { key: "kn", name: "Kannada" },
  { key: "kk", name: "Kazakh" },
  { key: "km", name: "Khmer" },
  { key: "ko", name: "Korean" },
  { key: "ku", name: "Kurdish" },
  { key: "ky", name: "Kyrgyz" },
  { key: "lo", name: "Lao" },
  { key: "la", name: "Latin" },
  { key: "lv", name: "Latvian" },
  { key: "lt", name: "Lithuanian" },
  { key: "lb", name: "Luxembourgish" },
  { key: "mk", name: "Macedonian" },
  { key: "mg", name: "Malagasy" },
  { key: "ms", name: "Malay" },
  { key: "ml", name: "Malayalam" },
  { key: "mt", name: "Maltese" },
  { key: "mi", name: "Maori" },
  { key: "mr", name: "Marathi" },
  { key: "mn", name: "Mongolian" },
  { key: "my", name: "Myanmar (Burmese)" },
  { key: "ne", name: "Nepali" },
  { key: "no", name: "Norwegian" },
  { key: "ny", name: "Nyanja (Chichewa)" },
  { key: "ps", name: "Pashto" },
  { key: "fa", name: "Persian" },
  { key: "pl", name: "Polish" },
  { key: "pt", name: "Portuguese (Portugal, Brazil)" },
  { key: "pa", name: "Punjabi" },
  { key: "ro", name: "Romanian" },
  { key: "ru", name: "Russian" },
  { key: "sm", name: "Samoan" },
  { key: "gd", name: "Scots Gaelic" },
  { key: "sr", name: "Serbian" },
  { key: "st", name: "Sesotho" },
  { key: "sn", name: "Shona" },
  { key: "sd", name: "Sindhi" },
  { key: "si", name: "Sinhala (Sinhalese)" },
  { key: "sk", name: "Slovak" },
  { key: "sl", name: "Slovenian" },
  { key: "so", name: "Somali" },
  { key: "es", name: "Spanish" },
  { key: "su", name: "Sundanese" },
  { key: "sw", name: "Swahili" },
  { key: "sv", name: "Swedish" },
  { key: "tl", name: "Tagalog (Filipino)" },
  { key: "tg", name: "Tajik" },
  { key: "ta", name: "Tamil" },
  { key: "te", name: "Telugu" },
  { key: "th", name: "Thai" },
  { key: "tr", name: "Turkish" },
  { key: "uk", name: "Ukrainian" },
  { key: "ur", name: "Urdu" },
  { key: "uz", name: "Uzbek" },
  { key: "vi", name: "Vietnamese" },
  { key: "cy", name: "Welsh" },
  { key: "xh", name: "Xhosa" },
  { key: "yi", name: "Yiddish" },
  { key: "yo", name: "Yoruba" },
  { key: "zu", name: "Zulu" },
];
